{
 "title": "sonic exporter",
 "tags": [
  "sre-foundations",
  "network",
  "sonic"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sonic_hw_psu_info,instance)"
    }
   },
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "crm_resource",
    "query": {
     "query": "label_values(sonic_crm_resource_available,resource)"
    }
   },
   {
    "name": "crm_acl_resource_target",
    "query": {
     "query": "label_values(sonic_crm_acl_resource_available,acl_target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput on $instance (pps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sonic_interface_receive_packets_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "RX {{device}}"
    },
    {
     "expr": "rate(sonic_interface_transmit_packets_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "TX {{device}}"
    }
   ]
  },
  {
   "title": "Throughput on $instance (bps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(sonic_interface_receive_bytes_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "RX {{device}}"
    },
    {
     "expr": "rate(sonic_interface_transmit_bytes_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "TX {{device}}"
    }
   ]
  },
  {
   "title": "Error rate on $instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sonic_interface_receive_errs_total{instance=\"$instance\",type=\"error\"}[$__rate_interval])",
     "legendFormat": "RX {{device}} {{type}}"
    },
    {
     "expr": "rate(sonic_interface_transmit_errs_total{instance=\"$instance\",type=\"error\"}[$__rate_interval])",
     "legendFormat": "TX {{device}} {{type}}"
    }
   ]
  },
  {
   "title": "Drop, discard rate on $instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sonic_interface_receive_errs_total{instance=\"$instance\",type=~\"drop|discard\"}[$__rate_interval])",
     "legendFormat": "RX {{device}} {{type}}"
    },
    {
     "expr": "rate(sonic_interface_transmit_errs_total{instance=\"$instance\",type=~\"drop|discard\"}[$__rate_interval])",
     "legendFormat": "TX {{device}} {{type}}"
    }
   ]
  },
  { "title": "Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Currently utilized shared buffer per port",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sonic_queue_shared_watermark_bytes_total{instance=\"$instance\"}",
     "legendFormat": "{{device}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Total shared buffer utilized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (sonic_queue_shared_watermark_bytes_total{instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Queue data rate (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(sonic_queue_bytes_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Queue data rate (pps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sonic_queue_packets_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Queue dropped rate (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(sonic_queue_dropped_bytes_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Queue dropped rate (pps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sonic_queue_dropped_packets_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Optical power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Optical power RX",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_receive_power_dbm{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optical power TX",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_transmit_power_dbm{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Optical power over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Optical power RX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_receive_power_dbm{instance=\"$instance\"}",
       "legendFormat": "RX{{unit}} - {{device}}"
      }
     ]
    },
    {
     "title": "Optical power TX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_transmit_power_dbm{instance=\"$instance\"}",
       "legendFormat": "TX{{unit}} - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSU operational satus",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sonic_hw_psu_operational_status{instance=\"$instance\"}",
       "legendFormat": "PSU{{slot}}"
      }
     ]
    },
    {
     "title": "PSU availability satus",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "sonic_hw_psu_available_status{instance=\"$instance\"}",
       "legendFormat": "PSU{{slot}}"
      }
     ]
    },
    {
     "title": "Fan operational satus",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sonic_hw_fan_operational_status{instance=\"$instance\"}",
       "legendFormat": "{{slot}} - {{name}}"
      }
     ]
    },
    {
     "title": "Fan availability satus",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "sonic_hw_fan_available_status{instance=\"$instance\"}",
       "legendFormat": "{{slot}} - {{name}}"
      }
     ]
    },
    {
     "title": "FAN speed RPM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sonic_hw_fan_rpm{instance=\"$instance\"}",
       "legendFormat": "{{slot}} - {{name}}"
      }
     ]
    },
    {
     "title": "PSU input volts",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_hw_psu_input_voltage_volts{instance=\"$instance\"}",
       "legendFormat": "PSU{{slot}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CRM ACL resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "$crm_acl_resource_target",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
     "repeat": "crm_acl_resource_target",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_crm_acl_resource_used{instance=\"$instance\",acl_target=\"$crm_acl_resource_target\"}/sonic_crm_acl_resource_available{instance=\"$instance\",acl_target=\"$crm_acl_resource_target\"}",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CRM resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "$crm_resource",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 388 },
     "repeat": "crm_resource",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_crm_resource_used{instance=\"$instance\",resource=\"$crm_resource\"}/sonic_crm_resource_available{instance=\"$instance\",resource=\"$crm_resource\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CRM resource usage over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "$crm_resource",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "repeat": "crm_resource",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonic_crm_resource_used{instance=\"$instance\",resource=\"$crm_resource\"}",
       "legendFormat": "{{resource}} used"
      },
      {
       "expr": "sonic_crm_resource_available{instance=\"$instance\",resource=\"$crm_resource\"}",
       "legendFormat": "{{resource}} available"
      }
     ]
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Collector scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sonic_hw_scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "HW collector"
    },
    {
     "expr": "sonic_interface_scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Interface collector"
    },
    {
     "expr": "sonic_crm_scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "CRM collector"
    },
    {
     "expr": "sonic_queue_scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Queue collector"
    }
   ]
  },
  {
   "title": "Interface collector status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonic_interface_collector_success{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRM collector status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonic_crm_collector_success{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HW collector status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonic_hw_collector_success{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue collector status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonic_queue_collector_success{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}